name: "Deploy API App Function"

on:
  workflow_dispatch:
  push:
    tags:
      # Trigger this workflow when a tag `azure-functions-api@<sem-ver>` is pushed
      # E.g.: `azure-functions-api@1.2.3` triggers the workflow; `azure-functions-api@1` does not.
      - 'azure-functions-api@[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: Deploy API
    concurrency:
      # This value must be equals to the one set in the DX Workflow: https://github.com/pagopa/dx/blob/51ca1/.github/workflows/function_app_deploy.yaml#L36C10-L36C35
      group: ${{ github.workflow }}-cd
      # Override this configuration to prevent cancelling a running deploy.
      cancel-in-progress: false
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@51ca10d1e4c97e8e987f14c14758bc8cf55fe79b
    secrets: inherit
    with:
      workspace_name: azure-functions-api
      environment: app-dev
      resource_group_name: io-d-eudiw-rg-01
      function_app_name: io-d-itn-eudiw-api-func-01
      health_check_path: "/info"
      use_private_agent: false
