name: "PR"

on:
  pull_request:
    paths:
      - apps/**
      - packages/**
      - yarn.lock
  workflow_dispatch: {}

jobs:
  code_review:
    uses: pagopa/dx/.github/workflows/js_code_review.yaml@5bdf3b27a027b5886fae83a6a66388c1da0642fd
    name: Code Review
    secrets: inherit
