name: GitHub Repo Builder

on:
  workflow_dispatch:
    inputs:
      technology:
        type: choice
        default: 'none'
        required: true
        description: 'Choose your technology stack'
        options:
          - none
      name:
        type: string
        required: true
        description: 'New repository name'

jobs:

  builder:
    name: 'Builder'
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    steps:

      - name: 'Create Blank Repository'
        if: inputs.technology == 'none'
        run: |
          gh repo create pagopa/${{ inputs.name }} \
            --disable-wiki \
            --public

      - name: 'Create Repository from Template'
        if: inputs.technology != 'none'
        run: |
          gh repo create pagopa/${{ inputs.name }} \
            --disable-wiki \
            --template pagopa/${{ inputs.technology }}-template \
            --public

  repo_setup:
    name: 'Repository setup'
    runs-on: ubuntu-20.04
    needs: [builder]
    if: inputs.technology != 'none'
    environment: prod-cd
    env:
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true
      ARM_STORAGE_USE_AZUREAD: true
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
      # we assume that the template repository contains this directory
      TEMPLATE_INFRA_DIR: repo/infra/repository
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        name: Checkout new repo
        with:
          repository: pagopa/${{ inputs.name }}
          path: repo
          token: ${{ env.GH_TOKEN }}

      - name: Replace placeholders
        working-directory: repo
        run: |
          find . -type f -exec sed -i 's/terraform-state-rg/dev-anderag/g; s/<your-environment>/prod/g; s/<your-project>/dotnet/g; s/<your-repo-name>/dotnet-app2/g' {} +

      - name: Push changes
        working-directory: repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "setup repo settings"
          git push origin main

      - name: Azure Login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3
        name: Setup Terraform

      - name: Terraform Init
        working-directory: ${{env.TEMPLATE_INFRA_DIR}}
        run: |
          terraform init

      - name: Terraform Plan
        working-directory: ${{env.TEMPLATE_INFRA_DIR}}
        run: |
          terraform plan \
            -lock-timeout=3000s \
            -input=false

      - name: Terraform Apply
        working-directory: ${{env.TEMPLATE_INFRA_DIR}}
        run: |
          terraform apply \
            -lock-timeout=3000s \
            -auto-approve \
            -input=false
